name = "mspled"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["mspled"]

[[depends-on]]
mspm0 = "~0.1.0-dev"
gnat_arm_elf = "^14.2.1"
bare_runtime = "~0.1.0"

[[pins]]
bare_runtime = { path='rts' }
mspm0 = { url='https://github.com/JeremyGrosser/mspm0.git' }

[configuration.values]
mspm0.Device = "MSPM0L1306"

[build-profiles]
"*" = "release"

[build-switches]
development.optimization = ["-Og", "-gnatn2"]
release.optimization = ["-Os", "-gnatn2", "-flto"]
# -flto requires modifying linker.xml to use gcc-ar and gcc-ranlib wrappers
# https://github.com/AdaCore/gprconfig_kb/commit/b5064577b7a990a4ee6c229aac4df7fb79917347

[gpr-set-externals]
BARE_RUNTIME_SWITCHES = "-mcpu=cortex-m0plus"
